# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' bivariate ecdf of numeric vectors x and y
becdf <- function(x, y) {
    .Call('cFDR_becdf', PACKAGE = 'cFDR', x, y)
}

<<<<<<< HEAD
#' univariate eCDF
#' calculate p(X<x) for fixed vector of points x
uecdf <- function(x) {
    .Call('cFDR_uecdf', PACKAGE = 'cFDR', x)
}

#' weighted eCDF
#' calculate p(X<x)(w) yfor fixed vectors of points x and weights w
wecdf <- function(x, w) {
    .Call('cFDR_wecdf', PACKAGE = 'cFDR', x, w)
}

#' conditional eCDF
=======
>>>>>>> f5ad236c4d30b49bf9bca0a33bc8087ebc743ec5
#' calculate p(X<x|Y<y) for fixed vectors of points x and y
cecdf <- function(x, y) {
    .Call('cFDR_cecdf', PACKAGE = 'cFDR', x, y)
}

#' find weighted mean of values of x either side of target
bestfit <- function(x, y, target) {
    .Call('cFDR_bestfit', PACKAGE = 'cFDR', x, y, target)
}

fdrp <- function(x) {
    .Call('cFDR_fdrp', PACKAGE = 'cFDR', x)
}

cecdf2 <- function(x1, x2, y1, y2) {
    .Call('cFDR_cecdf2', PACKAGE = 'cFDR', x1, x2, y1, y2)
}

rects <- function(x, y) {
    .Call('cFDR_rects', PACKAGE = 'cFDR', x, y)
}

