# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

becdf <- function(x, y) {
    .Call('cFDR_becdf', PACKAGE = 'cFDR', x, y)
}

cecdf <- function(x, y) {
    .Call('cFDR_cecdf', PACKAGE = 'cFDR', x, y)
}

